### ISSUE TITLE
Prompt 사용방법

### ISSUE THREAD

**Issue by tjgmlfbs124** [entrylabs/entry-modal#2]
안녕하세요
modal 모듈을 npm 로 install 했구요

import '@entrylabs/modal/dist/entry/entry-modal.css'
import { Alert, Confirm, Prompt } from '@entrylabs/modal';

이후에,

var modal = new Prompt({
            content : "123123",
            defaultValue : 'defaultValue',
            title : 'title',
            onEvent : {},
            options : {
              placeholder: "ppp",
              negativeButtonText: "negativeButtonText",
              positiveButtonText: "positiveButtonText"
            }
          });
modal.render();

이런식으로 사용을 하고싶어서 작업을 했는데, 나타나지 않네요..!
도움을 받을수 있을까요

**Comment by kimorkim** [comment]
@tjgmlfbs124 
안녕하세요. 
일단 import를 이용해서 사용하시면 react component가 나오게 됩니다.
사용법은 https://github.com/entrylabs/entry-modal#react-props 를 참고하시면 되며,
별도의 render등의 함수를 제공하지는 않습니다.
https://codesandbox.io/s/entry-modal-react-owr04에 example이 있으니 이를 참고해 보시기 바랍니다.

**Comment by tjgmlfbs124** [comment]
감사합니다 (__)
